#!/usr/bin/env bash
# This script creates an infinite loop that prints
# To infinity and beyond

trap 'echo "I am invincible!!!"' SIGTERM

count=1

while [ "$count" -eq 1 ]; do
	echo To infinity and beyond
	sleep 2
done
