#!/usr/bin/env bash
# This script displays Best School 10 times
# but says hi after the 9th time

count=0

while [[ "$count" -lt 10 ]]; do
	echo Best School
	if [[ "$count" -eq 8 ]]; then
		echo Hi
	fi
	count=$((count + 1))
done
		
