#!/usr/bin/env bash
# This script prints "Best School" 10 times but
# on the 4th iteration it print "Bad luck" and on 
# the eight iteration it prints "good luck"

count=0

while [[ "$count" -lt 10 ]]; do
	if [[ "$count" -eq 3 ]]; then
		echo bad luck
	elif [[ "$count" -eq 7 ]]; then
		echo good luck
	else
		echo Best School
	fi
	count=$((count + 1))
done
